### ISSUE TITLE
Submitting Segment gives Status 500, Afterwards Sponsorblock Button dissapears

### ISSUE THREAD

**Issue by DrDragonKiller** [YTVanced/SponsorBlock#50] opened 2021-08-09 15:38 UTC
On nonroot Version 15.43.32 there was no problem.
On both root and nonroot Version 16.29.39 when submitting a segment it gives status 500 on both WiFi and cellular.
Furthermore then the sponsorblock button just dissapears and only reappears when closing the video player and reopening a video.

**Comment by caneleex** [comment] 2021-08-09 16:00
can you give me the video you're trying to submit segments on?

**Comment by abidjauhar17** [comment] 2021-08-09 16:26
same
I also have a 500 error when I want to send a segment

**Comment by caneleex** [comment] 2021-08-09 16:28
give me the video examples, timings would be great too.

**Comment by abidjauhar17** [comment] 2021-08-09 16:34
![image](https://user-images.githubusercontent.com/37255346/128741196-ce3faf6a-c05e-45cd-961b-e9e7efef306a.png)
![image](https://user-images.githubusercontent.com/37255346/128741215-bfde2af9-d290-4953-bba4-c3910e40a5f5.png)

sorry i use indonesian
basically in the second picture it says error message can't send segment: status 500

**Comment by caneleex** [comment] 2021-08-10 10:44
can you give me the timings that give you code 500? I can't reproduce this

**Comment by abidjauhar17** [comment] 2021-08-10 10:46
> can you give me the timings that give you code 500? I can't reproduce this

Everywhere.. I tried at the beginning and end, but the same error

**Comment by caneleex** [comment] 2021-08-10 11:35
I can't reproduce this locally, please give me the **exact timings** that give you 500.

**Comment by caneleex** [comment] 2021-08-10 11:56
resolved in https://github.com/YTVanced/SponsorBlock/commit/8cd13409ba9f3827a3800fb15c09eabd91e4dcb9

**Closed by caneleex** 2021-08-10 11:57 UTC

**Comment by abidjauhar17** [comment] 2021-08-10 12:04
> ~I can't reproduce this locally, please give me the **exact timings** that give you 500.~
> 
> nevermind, I think I know what the issue is.

How to fix it? How to use the code you uploaded

**Comment by caneleex** [comment] 2021-08-10 12:06
you can either build the source yourself or wait for another vanced release. you can temporarily fix this by switching your phone's language to English.

**Comment by abidjauhar17** [comment] 2021-08-10 12:11
> you can either build the source yourself or wait for another vanced release. you can temporarily fix this by switching your phone's language to English.

When will the fix be uploaded? Will it be a long wait along with the upcoming new vanced version?

**Comment by caneleex** [comment] 2021-08-10 12:13
we don't know.

**Comment by DrDragonKiller** [comment] 2021-08-11 16:40
Can confirm changing phone language from German to English fixed the problem, thanks a lot!

**Comment by shon4840** [comment] 2022-01-24 10:51
how to install sponsorblock in youtube vanced?
