### ISSUE TITLE
Toggle SponsorBlock auto ad skipping

### ISSUE THREAD

**Issue by Combinacijus** [YTVanced/SponsorBlock#55] opened 2021-09-20 23:13 UTC
Sometimes important parts of video are mislabeled as an ad so it would be nice if there was a toggle on video overlay to stop skipping ads

(Not sure if this is right place for SponsorBlock suggestions so please redirect me if needed)

**Comment by caneleex** [comment] 2021-09-21 21:18
duplicate of #32 

you can report mislabeled segments on [SponsorBlock Discord](https://discord.gg/sponsorblock)

**Closed by caneleex** 2021-09-21 21:18 UTC
